"""Catalog of refusal and result codes. Not a scoring system."""

from __future__ import annotations

REASON_CODES = frozenset(
    {
        "CHANGE_DISCONTINUITY",
        "CHECKSUM_MISMATCH",
        "CONTRADICTORY_IDENTITY",
        "CONTRADICTORY_PAYLOAD",
        "DATASET_DECLARATION_MISMATCH",
        "DECLARATION_FILE_MISSING",
        "DUPLICATE_MARKET_TIMESTAMP",
        "ENVELOPE_NOT_JSON_OBJECT",
        "INVALID_CLOSE",
        "INVALID_HIGH",
        "INVALID_LOW",
        "INVALID_MARKET_TIMESTAMP",
        "INVALID_OBSERVATION",
        "INVALID_OPEN",
        "INVALID_RETRIEVAL_TIMESTAMP",
        "INVALID_VOLUME",
        "MALFORMED_CHECKSUM",
        "MALFORMED_CONTEXT_DECISION_USE_TAG",
        "MISSING_CHECKSUM",
        "MISSING_CLOSE",
        "MISSING_DECLARATION_FIELD",
        "MISSING_ENVELOPE",
        "MISSING_INTERVAL",
        "MISSING_MARKET_TIMESTAMP",
        "MISSING_PAYLOAD",
        "MISSING_PROVENANCE_CLASS",
        "MISSING_PROVIDER",
        "MISSING_SYMBOL_OR_UNIVERSE",
        "MISSING_TIMEZONE",
        "MISSING_TRANSFORMATION_VERSION",
        "OBSERVATION_NOT_ADMITTED",
        "OHLC_CONTRADICTION",
        "PACK_EXPORT_DIRECTORY_NOT_EMPTY",
        "PACK_EXPORT_PATH_IS_FILE",
        "PACK_NOT_USABLE",
        "PACK_PROVENANCE_NOT_ALLOWED",
        "REGISTRY_PATH_IS_DIRECTORY",
        "PAYLOAD_CHECKSUM_MISMATCH",
        "PAYLOAD_NOT_JSON_OBJECT",
        "SESSION_REPORT_PATH_IS_DIRECTORY",
        "SNAPSHOT_CHECKSUM_MISMATCH",
        "SNAPSHOT_PATH_IS_DIRECTORY",
        "TIMEZONE_MISMATCH",
        "UNKNOWN_PROVENANCE_CLASS",
        "UNKNOWN_TIMEZONE",
        "UNREADABLE_DECLARATION",
        "UNREADABLE_ITEM",
        "UNREADABLE_JSON",
        "UNREADABLE_PACK",
        "UNREADABLE_REGISTRY_FILE",
        "UNREADABLE_SNAPSHOT_FILE",
    }
)

RESULT_STATUSES = frozenset(
    {
        "INSUFFICIENT_EVIDENCE",
        "INVALID_COMPARISON",
        "MEASURED",
        "UNCLEAR",
    }
)
